language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.target'

script: "./mvnw clean package"

before_install:
  - chmod +x mvnw

