spring:
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    platform: mariadb
    url: jdbc:mariadb:failover://localhost:3306/erooja_test?autoReconnect=true
    username: root
    password:
    driverClassName: org.mariadb.jdbc.Driver
