server:
  port: 20000

  tomcat:
    accesslog:
      enabled: true
      pattern: common
      encoding: utf-8

spring:
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
      hibernate.default_batch_fetch_size: 1000

  datasource:
    platform: mariadb
    url: jdbc:mariadb:failover://localhost:3306/erooja_test?autoReconnect=true
    username: root
    password:
    driverClassName: org.mariadb.jdbc.Driver

  data:
    rest:
      basePath=/api

jwt:
  secret: jwtLocalSecret

thirdPartyProperties:
  kakaoAdminKey: ${KAKAO_ADMIN_KEY:}
  kakaoRestKey: ${KAKAO_REST_API_KEY:}

amazonProperties:
  endpointUrl: https://s3.ap-northeast-2.amazonaws.com
  accessKey: ${AWS_S3_ACCESS_KEY:}
  secretKey: ${AWS_S3_SECRET_KEY:}
  bucketName: erooja-user-files