spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    platform: org.hibernate.dialect.H2Dialect
    url: jdbc:h2:mem:erooja-test
    username: sa
    password:
    driverClassName: org.h2.Driver