server:
  port: 20000

  tomcat:
    accesslog:
      enabled: true
      pattern: common
      encoding: utf-8

spring:
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: false
        format_sql: false

  datasource:
    platform: mariadb
    url: jdbc:mariadb:failover://localhost:3306/erooja_test?autoReconnect=true
    username: root
    password:
    driverClassName: org.mariadb.jdbc.Driver

  data:
    rest:
      basePath=/api

jwt:
  secret: jwtLocalSecret

